version: '3'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  news_service:
    container_name: news-service-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    restart: unless-stopped