version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mail-service-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    command: mongod --auth

  mail_service:
    container_name: mail-service-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: unless-stopped